TILESIZE = 25
NUM_COLUMNS = 19
NUM_ROWS = 17
WIDTH = NUM_COLUMNS * TILESIZE
HEIGHT = NUM_ROWS * TILESIZE

WINDOW_NAME = 'THIN ICE'

MAX_LEVEL = 12
FIRST_LEVEL = 1
LEVEL_UP_POINTS = 100
FLOOR_KILL_POINTS = 10
TREASURE_POINTS = 50

TARGET = "TARGET"
FLOOR = "FLOOR"
ICE = "ICE"
GOLDEN_KEY = "GOLDEN_KEY"
KEY_HOLE = "KEY_HOLE"
TREASURE = "TREASURE"

TEXTFONT = 'data/font/arcade.ttf'
FONTSIZE = 20

LEFT_TEXT_POSITION = (79, 12.5)
CENTER_TEXT_POSITION = (237.5, 12.5)
RIGHT_TEXT_POSITION = (395.83, 12.5)
LEFT_BOTTOM_TEXT_POSITION = (79, HEIGHT - 12.5)
RIGHT_BOTTOM_TEXT_POSITION = (395.83, HEIGHT - 12.5)

BLUE = (0, 0, 255)
BACKGROUNDCOLOR = (112, 181, 253)

TEXT_COLOR = BLUE

REWARD_FOR_BREAKING_FLOOR = 0.1
# REWARD_FOR_BREAKING_ICE = 0
REWARD_FOR_PEAKING_UP_A_TREASURE = 0.75
# REWARD_FOR_PEAKING_UP_A_KEY = 0
# REWARD_FOR_UNLOCKING_A_DOOR = 0

REWARD_FOR_COMPLETING_A_LEVEL = 0.85
REWARD_FOR_BREAKING_ALL_THE_FLOORS = 1
REWARD_FOR_GOING_TO_WATER = -0.75
REWARD_FOR_BECOMING_STUCK = -0.80
REWARD_FOR_GOING_TO_WALL = -0.85